/*
 * @Descripttion: 
 * @Author: Xvsenfeng helloworldjiao@163.com
 * @LastEditors: Please set LastEditors
 * Copyright (c) 2025 by helloworldjiao@163.com, All Rights Reserved. 
 */

#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_40
#define AUDIO_I2S_GPIO_WS GPIO_NUM_45
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_39
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_38
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_48

#define AUDIO_CODEC_PA_PIN GPIO_NUM_46
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_21
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_47
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO GPIO_NUM_17
#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define BUTTON_KEY1_GPIO GPIO_NUM_1
#define BUTTON_KEY2_GPIO GPIO_NUM_2

#define CHARGING_GPIO GPIO_NUM_41
#define DONE_GPIO GPIO_NUM_42

#define RESET_NVS_BUTTON_GPIO GPIO_NUM_NC
#define RESET_FACTORY_BUTTON_GPIO GPIO_NUM_NC

#define BATTERY_ADC_PIN GPIO_NUM_3

#define DISPLAY_SPI_SCK_PIN GPIO_NUM_13
#define DISPLAY_SPI_MOSI_PIN GPIO_NUM_14
#define DISPLAY_DC_PIN GPIO_NUM_15
#define DISPLAY_SPI_CS_PIN GPIO_NUM_16
#define DISPLAY_RES GPIO_NUM_NC
#define DISPLAY_BLK GPIO_NUM_4
#define DISPLAY_WIDTH 240
#define DISPLAY_HEIGHT 280
#define DISPLAY_SWAP_XY false
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define BACKLIGHT_INVERT false

#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 20
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_4
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false


/**< Display P169H002-CTP-Touch */
#define DISPLAY_TOUCH_AS_LISTEN_BUTTON 1
#define DISPLAY_TOUCH_SDA           GPIO_NUM_6
#define DISPLAY_TOUCH_SCL           GPIO_NUM_7
#define DISPLAY_TOUCH_INT           GPIO_NUM_NC // GPIO_NUM_18

#define BSP_SD_CLK          (GPIO_NUM_17)
#define BSP_SD_CMD          (GPIO_NUM_5)
#define BSP_SD_D0           (GPIO_NUM_18)
#define MOUNT_POINT              "/sdcard"

#endif // _BOARD_CONFIG_H_
